package cnr.rubicon.migFiles;
/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'ReadUpdatesMsg'
 * message type.
 */

public class ReadUpdatesMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 5;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 36;

    /** Create a new ReadUpdatesMsg of size 5. */
    public ReadUpdatesMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new ReadUpdatesMsg of the given data_length. */
    public ReadUpdatesMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ReadUpdatesMsg with the given data_length
     * and base offset.
     */
    public ReadUpdatesMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ReadUpdatesMsg using the given byte array
     * as backing store.
     */
    public ReadUpdatesMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ReadUpdatesMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public ReadUpdatesMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ReadUpdatesMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public ReadUpdatesMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ReadUpdatesMsg embedded in the given message
     * at the given base offset.
     */
    public ReadUpdatesMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new ReadUpdatesMsg embedded in the given message
     * at the given base offset and length.
     */
    public ReadUpdatesMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <ReadUpdatesMsg> \n";
      try {
        s += "  [type=0x"+Long.toHexString(get_type())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [sampling_rate=0x"+Long.toHexString(get_sampling_rate())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [transducers=0x"+Long.toHexString(get_transducers())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: type
    //   Field type: short, unsigned
    //   Offset (bits): 0
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'type' is signed (false).
     */
    public static boolean isSigned_type() {
        return false;
    }

    /**
     * Return whether the field 'type' is an array (false).
     */
    public static boolean isArray_type() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'type'
     */
    public static int offset_type() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'type'
     */
    public static int offsetBits_type() {
        return 0;
    }

    /**
     * Return the value (as a short) of the field 'type'
     */
    public short get_type() {
        return (short)getUIntBEElement(offsetBits_type(), 8);
    }

    /**
     * Set the value of the field 'type'
     */
    public void set_type(short value) {
        setUIntBEElement(offsetBits_type(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'type'
     */
    public static int size_type() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'type'
     */
    public static int sizeBits_type() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: sampling_rate
    //   Field type: int, unsigned
    //   Offset (bits): 8
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'sampling_rate' is signed (false).
     */
    public static boolean isSigned_sampling_rate() {
        return false;
    }

    /**
     * Return whether the field 'sampling_rate' is an array (false).
     */
    public static boolean isArray_sampling_rate() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'sampling_rate'
     */
    public static int offset_sampling_rate() {
        return (8 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'sampling_rate'
     */
    public static int offsetBits_sampling_rate() {
        return 8;
    }

    /**
     * Return the value (as a int) of the field 'sampling_rate'
     */
    public int get_sampling_rate() {
        return (int)getUIntBEElement(offsetBits_sampling_rate(), 16);
    }

    /**
     * Set the value of the field 'sampling_rate'
     */
    public void set_sampling_rate(int value) {
        setUIntBEElement(offsetBits_sampling_rate(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'sampling_rate'
     */
    public static int size_sampling_rate() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'sampling_rate'
     */
    public static int sizeBits_sampling_rate() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: transducers
    //   Field type: int, unsigned
    //   Offset (bits): 24
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'transducers' is signed (false).
     */
    public static boolean isSigned_transducers() {
        return false;
    }

    /**
     * Return whether the field 'transducers' is an array (false).
     */
    public static boolean isArray_transducers() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'transducers'
     */
    public static int offset_transducers() {
        return (24 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'transducers'
     */
    public static int offsetBits_transducers() {
        return 24;
    }

    /**
     * Return the value (as a int) of the field 'transducers'
     */
    public int get_transducers() {
        return (int)getUIntBEElement(offsetBits_transducers(), 16);
    }

    /**
     * Set the value of the field 'transducers'
     */
    public void set_transducers(int value) {
        setUIntBEElement(offsetBits_transducers(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'transducers'
     */
    public static int size_transducers() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'transducers'
     */
    public static int sizeBits_transducers() {
        return 16;
    }

}
