/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'SerialJoinedMsg'
 * message type.
 */

public class SerialJoinedMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 9;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 16;

    /** Create a new SerialJoinedMsg of size 9. */
    public SerialJoinedMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new SerialJoinedMsg of the given data_length. */
    public SerialJoinedMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SerialJoinedMsg with the given data_length
     * and base offset.
     */
    public SerialJoinedMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SerialJoinedMsg using the given byte array
     * as backing store.
     */
    public SerialJoinedMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SerialJoinedMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public SerialJoinedMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SerialJoinedMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public SerialJoinedMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SerialJoinedMsg embedded in the given message
     * at the given base offset.
     */
    public SerialJoinedMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SerialJoinedMsg embedded in the given message
     * at the given base offset and length.
     */
    public SerialJoinedMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <SerialJoinedMsg> \n";
      try {
        s += "  [msg_type=0x"+Long.toHexString(get_msg_type())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [island_addr=0x"+Long.toHexString(get_island_addr())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [mote_addr=0x"+Long.toHexString(get_mote_addr())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [mote_type=0x"+Long.toHexString(get_mote_type())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [transducers=0x"+Long.toHexString(get_transducers())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [actuators=0x"+Long.toHexString(get_actuators())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: msg_type
    //   Field type: byte, unsigned
    //   Offset (bits): 0
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'msg_type' is signed (false).
     */
    public static boolean isSigned_msg_type() {
        return false;
    }

    /**
     * Return whether the field 'msg_type' is an array (false).
     */
    public static boolean isArray_msg_type() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'msg_type'
     */
    public static int offset_msg_type() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'msg_type'
     */
    public static int offsetBits_msg_type() {
        return 0;
    }

    /**
     * Return the value (as a byte) of the field 'msg_type'
     */
    public byte get_msg_type() {
        return (byte)getSIntBEElement(offsetBits_msg_type(), 8);
    }

    /**
     * Set the value of the field 'msg_type'
     */
    public void set_msg_type(byte value) {
        setSIntBEElement(offsetBits_msg_type(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'msg_type'
     */
    public static int size_msg_type() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'msg_type'
     */
    public static int sizeBits_msg_type() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: island_addr
    //   Field type: int, unsigned
    //   Offset (bits): 8
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'island_addr' is signed (false).
     */
    public static boolean isSigned_island_addr() {
        return false;
    }

    /**
     * Return whether the field 'island_addr' is an array (false).
     */
    public static boolean isArray_island_addr() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'island_addr'
     */
    public static int offset_island_addr() {
        return (8 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'island_addr'
     */
    public static int offsetBits_island_addr() {
        return 8;
    }

    /**
     * Return the value (as a int) of the field 'island_addr'
     */
    public int get_island_addr() {
        return (int)getUIntBEElement(offsetBits_island_addr(), 16);
    }

    /**
     * Set the value of the field 'island_addr'
     */
    public void set_island_addr(int value) {
        setUIntBEElement(offsetBits_island_addr(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'island_addr'
     */
    public static int size_island_addr() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'island_addr'
     */
    public static int sizeBits_island_addr() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: mote_addr
    //   Field type: int, unsigned
    //   Offset (bits): 24
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'mote_addr' is signed (false).
     */
    public static boolean isSigned_mote_addr() {
        return false;
    }

    /**
     * Return whether the field 'mote_addr' is an array (false).
     */
    public static boolean isArray_mote_addr() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'mote_addr'
     */
    public static int offset_mote_addr() {
        return (24 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'mote_addr'
     */
    public static int offsetBits_mote_addr() {
        return 24;
    }

    /**
     * Return the value (as a int) of the field 'mote_addr'
     */
    public int get_mote_addr() {
        return (int)getUIntBEElement(offsetBits_mote_addr(), 16);
    }

    /**
     * Set the value of the field 'mote_addr'
     */
    public void set_mote_addr(int value) {
        setUIntBEElement(offsetBits_mote_addr(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'mote_addr'
     */
    public static int size_mote_addr() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'mote_addr'
     */
    public static int sizeBits_mote_addr() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: mote_type
    //   Field type: short, unsigned
    //   Offset (bits): 40
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'mote_type' is signed (false).
     */
    public static boolean isSigned_mote_type() {
        return false;
    }

    /**
     * Return whether the field 'mote_type' is an array (false).
     */
    public static boolean isArray_mote_type() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'mote_type'
     */
    public static int offset_mote_type() {
        return (40 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'mote_type'
     */
    public static int offsetBits_mote_type() {
        return 40;
    }

    /**
     * Return the value (as a short) of the field 'mote_type'
     */
    public short get_mote_type() {
        return (short)getUIntBEElement(offsetBits_mote_type(), 8);
    }

    /**
     * Set the value of the field 'mote_type'
     */
    public void set_mote_type(short value) {
        setUIntBEElement(offsetBits_mote_type(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'mote_type'
     */
    public static int size_mote_type() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'mote_type'
     */
    public static int sizeBits_mote_type() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: transducers
    //   Field type: int, unsigned
    //   Offset (bits): 48
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'transducers' is signed (false).
     */
    public static boolean isSigned_transducers() {
        return false;
    }

    /**
     * Return whether the field 'transducers' is an array (false).
     */
    public static boolean isArray_transducers() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'transducers'
     */
    public static int offset_transducers() {
        return (48 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'transducers'
     */
    public static int offsetBits_transducers() {
        return 48;
    }

    /**
     * Return the value (as a int) of the field 'transducers'
     */
    public int get_transducers() {
        return (int)getUIntBEElement(offsetBits_transducers(), 16);
    }

    /**
     * Set the value of the field 'transducers'
     */
    public void set_transducers(int value) {
        setUIntBEElement(offsetBits_transducers(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'transducers'
     */
    public static int size_transducers() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'transducers'
     */
    public static int sizeBits_transducers() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: actuators
    //   Field type: short, unsigned
    //   Offset (bits): 64
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'actuators' is signed (false).
     */
    public static boolean isSigned_actuators() {
        return false;
    }

    /**
     * Return whether the field 'actuators' is an array (false).
     */
    public static boolean isArray_actuators() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'actuators'
     */
    public static int offset_actuators() {
        return (64 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'actuators'
     */
    public static int offsetBits_actuators() {
        return 64;
    }

    /**
     * Return the value (as a short) of the field 'actuators'
     */
    public short get_actuators() {
        return (short)getUIntBEElement(offsetBits_actuators(), 8);
    }

    /**
     * Set the value of the field 'actuators'
     */
    public void set_actuators(short value) {
        setUIntBEElement(offsetBits_actuators(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'actuators'
     */
    public static int size_actuators() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'actuators'
     */
    public static int sizeBits_actuators() {
        return 8;
    }

}
