//
//  TransportMD.nc
//  RUBICON src
//
//  Created by Claudio Vairo on 08/02/13.
//  Copyright (c) 2013 ISTI-CNR. All rights reserved.
//


/**
 * Interface of the Communication layer for the Transport Message Dispatcher component.
 */

interface TransportMD {
    
    /**
	 * Forwards the given message to the Network layer. It returns the sequence number generated by the Network layer.
	 *
	 * @param dest (input) The RUBICON address of the destionation of the message. 
     * If the devid field is null, it addresses a PC or a Robot.
	 *
	 * @param payload (input) Pointer to a region where the data to be sent are stored.
	 *
	 * @param nbytes (input) Number of bytes of the payload.
	 *
	 * @param reliable (input) TRUE if an ack is requested for the current message.
     * 
     * @param comp_id (input) The identifier of the Transport-level component sending the message.
     * It is used at destination side to dispatch the message to the right Transport-level component.
	 *
	 * @return the sequence number generated for that message.
	 */
    command uint16_t send(r_addr_t dest, int8_t* payload, uint8_t nbytes, bool reliable, uint8_t comp_id);


    /**
	 * Notifies the reception of the given message from the specified source to the proper Transport component according to the Transport comp_id (Trans_ID) field extracted from the payload. 
	 *
	 * @param sender (output) The RUBICON address of the source of the message.
	 *
	 * @param payload (output) Pointer to the received message.
	 *
	 * @param nbytes (output) Number of bytes of the received payload.
     *
     * @param reliable (output) TRUE if an ack is requested for the received message.
     *
     * @param seqnum (output) the sequence number of the received message.
	 */
    event void receive(r_addr_t sender, int8_t* payload, uint8_t nbytes, bool reliable, uint16_t seqnum);

}
